version: "3.9"

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: db
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
