version: "3.9"

services:
  db:
    build: ./db
    container_name: postgis
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fastapi
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: nextjs
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
